-- ============================================
-- E-Commerce Sales Analysis
-- Business Insight Queries
-- ============================================

-- Q1: Customers who belong to a particular city (Bengaluru)
SELECT * FROM customers WHERE city = 'Bengaluru';

-- Q2: Products that cost more than 1000, sorted by price descending
SELECT product_id, product_name, category, price
FROM products
WHERE price > 1000
ORDER BY price DESC;

-- Q3: Full name of each customer
SELECT CONCAT(first_name, ' ', last_name) AS full_name
FROM customers;

-- Q4: Customers who have registered and placed at least one order
SELECT DISTINCT c.customer_id, c.first_name, c.last_name
FROM customers c
INNER JOIN orders o
ON c.customer_id = o.customer_id;

-- Q5: Number of orders placed by each customer
SELECT customer_id, COUNT(*) AS total_orders
FROM orders
GROUP BY customer_id;

-- Q6: Customers who have placed more than 2 orders
SELECT customer_id, COUNT(*) AS total_orders
FROM orders
GROUP BY customer_id
HAVING COUNT(*) > 2;

-- Q7: Total quantity sold for each product
SELECT product_id, SUM(quantity) AS total_quantity_sold
FROM order_details
GROUP BY product_id;

-- Q8: Total revenue generated by each product, highest to lowest
SELECT product_id, SUM(quantity * unit_price) AS total_revenue
FROM order_details
GROUP BY product_id
ORDER BY total_revenue DESC;

-- Q9: Best-selling product by quantity
SELECT product_id, SUM(quantity) AS total_quantity
FROM order_details
GROUP BY product_id
ORDER BY total_quantity DESC
LIMIT 1;

-- Q10: Customers whose total order value is greater than 10000
SELECT o.customer_id, SUM(od.quantity * od.unit_price) AS total_order_value
FROM orders o
INNER JOIN order_details od
ON o.order_id = od.order_id
GROUP BY o.customer_id
HAVING SUM(od.quantity * od.unit_price) > 10000;

-- Q11: Highest-priced product in each category
SELECT category, MAX(price) AS highest_price
FROM products
GROUP BY category;

-- Q12: Products priced above the average product price
SELECT product_id, product_name, price
FROM products
WHERE price > (SELECT AVG(price) FROM products);

-- Q13: Customer who placed the highest-value order
SELECT o.customer_id, o.order_id, SUM(od.quantity * od.unit_price) AS order_value
FROM orders o
INNER JOIN order_details od
ON o.order_id = od.order_id
GROUP BY o.customer_id, o.order_id
ORDER BY order_value DESC
LIMIT 1;

-- Q14: Total sales for each month
SELECT YEAR(o.order_date) AS sales_year,
       MONTH(o.order_date) AS sales_month,
       SUM(od.quantity * od.unit_price) AS total_sales
FROM orders o
INNER JOIN order_details od
ON o.order_id = od.order_id
GROUP BY YEAR(o.order_date), MONTH(o.order_date)
ORDER BY sales_year, sales_month;

-- Q15: Whether total revenue has crossed 100000
SELECT SUM(amount) AS total_revenue,
       IF(SUM(amount) > 100000,
          'Revenue Crossed 100000',
          'Revenue Not Crossed 100000') AS revenue_status
FROM payments;

-- Q16: Rank products by revenue using a window function
SELECT product_id,
       SUM(quantity * unit_price) AS revenue,
       RANK() OVER (ORDER BY SUM(quantity * unit_price) DESC) AS revenue_rank
FROM order_details
GROUP BY product_id;

-- Q17: Orders placed on or after 1st January 2026 (with index for performance)
CREATE INDEX idx_order_date ON orders(order_date);

SELECT *
FROM orders
WHERE order_date >= '2026-01-01';

-- Q18: View for high-value orders (order value > 10000) with customer ID
CREATE VIEW high_value_orders AS
SELECT o.order_id,
       o.customer_id,
       SUM(od.quantity * od.unit_price) AS order_value
FROM orders o
INNER JOIN order_details od
ON o.order_id = od.order_id
GROUP BY o.order_id, o.customer_id
HAVING SUM(od.quantity * od.unit_price) > 10000;

SELECT * FROM high_value_orders;

-- Q19: Products that have never been ordered (LEFT JOIN)
SELECT p.product_id, p.product_name
FROM products p
LEFT JOIN order_details od
ON p.product_id = od.product_id
WHERE od.product_id IS NULL;

-- Q20: Stored procedure to fetch orders within a date range
DELIMITER //
CREATE PROCEDURE orders_by_date(
    IN start_date DATE,
    IN end_date DATE
)
BEGIN
    SELECT *
    FROM orders
    WHERE order_date BETWEEN start_date AND end_date;
END //
DELIMITER ;

CALL orders_by_date('2026-03-01', '2026-03-31');
